package pecker.mybatis.entity;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.id
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.province_name
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.area
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.mall_code
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    private String mallCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.id
     *
     * @return the value of province.id
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.id
     *
     * @param id the value for province.id
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.province_name
     *
     * @return the value of province.province_name
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.province_name
     *
     * @param provinceName the value for province.province_name
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.area
     *
     * @return the value of province.area
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.area
     *
     * @param area the value for province.area
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.mall_code
     *
     * @return the value of province.mall_code
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    public String getMallCode() {
        return mallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.mall_code
     *
     * @param mallCode the value for province.mall_code
     *
     * @mbggenerated Tue Aug 21 19:36:13 CST 2018
     */
    public void setMallCode(String mallCode) {
        this.mallCode = mallCode == null ? null : mallCode.trim();
    }
}